version: '3.7'
services:
    postgres:
        image: postgres:10.5
        container_name: postgres
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: 30s
          timeout: 30s
          retries: 3
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=elephant
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'
        volumes: 
          - ./scripts/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
          
    